package sdstorecli;

import static javax.xml.ws.BindingProvider.ENDPOINT_ADDRESS_PROPERTY;

import java.util.Map;

import javax.xml.ws.BindingProvider;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

import pt.ulisboa.tecnico.sdis.store.ws.DocAlreadyExists_Exception;
import pt.ulisboa.tecnico.sdis.store.ws.DocUserPair;
import pt.ulisboa.tecnico.sdis.store.ws.SDStore; // classes generated by wsimport from WSDL
import pt.ulisboa.tecnico.sdis.store.ws.SDStore_Service;
import sdstorecli.uddi.UDDINaming;

/**
 * Test suite
 */
public class CreateDocTest {

    // static members

    private static SDStore port;
    private static String userId = "CreateTest";
    private static String documentId = "CreateTestDoc";
    private static int testNumber;

    // one-time initialization and clean-up

    @BeforeClass
    public static void oneTimeSetUp() throws Exception {
        SDStore_Service service = new SDStore_Service();
        port = service.getSDStoreImplPort();
        UDDINaming uddiNaming = new UDDINaming("http://localhost:8081");
        String endpointAddress = uddiNaming.lookup("sd-store");
        BindingProvider bindingProvider = (BindingProvider) port;
        Map<String, Object> requestContext = bindingProvider.getRequestContext();
        requestContext.put(ENDPOINT_ADDRESS_PROPERTY, endpointAddress);
        testNumber = 0;
    }

    @AfterClass
    public static void oneTimeTearDown() {
        port = null;
    }

    // members

    private static DocUserPair pair;

    // initialization and clean-up for each test

    @Before
    public void setUp() {
        pair = new DocUserPair();
        pair.setDocumentId(documentId + testNumber);
        pair.setUserId(userId + testNumber);
    }

    @After
    public void tearDown() {
        testNumber++;
        pair = null;
    }

    // Success
    @Test
    public void testCreateDoc() throws Exception {
        port.createDoc(pair);
    }

    // Fail - Duplicate document
    @Test(expected = DocAlreadyExists_Exception.class)
    public void testDuplicateDoc() throws Exception {
        port.createDoc(pair);
        port.createDoc(pair);
    }

}
