package sdstorecli;

import static javax.xml.ws.BindingProvider.ENDPOINT_ADDRESS_PROPERTY;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import javax.xml.ws.BindingProvider;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Assert;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

import pt.ulisboa.tecnico.sdis.store.ws.DocUserPair;
import pt.ulisboa.tecnico.sdis.store.ws.SDStore; // classes generated by wsimport from WSDL
import pt.ulisboa.tecnico.sdis.store.ws.SDStore_Service;
import pt.ulisboa.tecnico.sdis.store.ws.UserDoesNotExist_Exception;
import sdstorecli.uddi.UDDINaming;

/**
 * Test suite
 */
public class ListDocsTest {

    // static members

    private static SDStore port;
    private static String userId = "ListDocsTest";
    private static String documentId = "ListDocsTestDoc";
    private static int testNumber;

    // one-time initialization and clean-up

    @BeforeClass
    public static void oneTimeSetUp() throws Exception {
        SDStore_Service service = new SDStore_Service();
        port = service.getSDStoreImplPort();
        UDDINaming uddiNaming = new UDDINaming("http://localhost:8081");
        String endpointAddress = uddiNaming.lookup("sd-store");
        BindingProvider bindingProvider = (BindingProvider) port;
        Map<String, Object> requestContext = bindingProvider.getRequestContext();
        requestContext.put(ENDPOINT_ADDRESS_PROPERTY, endpointAddress);
        testNumber = 0;
    }

    @AfterClass
    public static void oneTimeTearDown() {
        port = null;
    }

    // members

    private static DocUserPair pair;

    // initialization and clean-up for each test

    @Before
    public void setUp() {
        pair = new DocUserPair();
        pair.setDocumentId(documentId + testNumber);
        pair.setUserId(userId + testNumber);
    }

    @After
    public void tearDown() {
        testNumber++;
        pair = null;
    }

    // Success
    @Test
    public void testListDocs() throws Exception {
        port.createDoc(pair);
        List<String> correctList = new ArrayList<String>();
        correctList.add(documentId + testNumber);
        List<String> resultList = port.listDocs(userId + testNumber);
        Assert.assertEquals(correctList, resultList);
    }

    // Fail - Unknown UserId
    @Test(expected = UserDoesNotExist_Exception.class)
    public void testListDocsUnknownUser() throws Exception {
        port.listDocs(userId + testNumber);
    }

}
