package sdstorecli;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

import java.net.ConnectException;

import javax.xml.registry.JAXRException;
import javax.xml.ws.WebServiceException;

import mockit.Expectations;
import mockit.Mock;
import mockit.MockUp;
import mockit.Mocked;
import mockit.NonStrictExpectations;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

import pt.ulisboa.tecnico.sdis.store.ws.DocAlreadyExists_Exception;
import pt.ulisboa.tecnico.sdis.store.ws.DocUserPair;
import pt.ulisboa.tecnico.sdis.store.ws.SDStore;
import pt.ulisboa.tecnico.sdis.store.ws.SDStore_Service;
import sdstorecli.uddi.UDDINaming;

// classes generated by wsimport from WSDL

/**
 * Test suite
 */
public class StoreClientTest {

    // static members
    private static int x = 1;

    // one-time initialization and clean-up

    @BeforeClass
    public static void oneTimeSetUp() {
    }

    @AfterClass
    public static void oneTimeTearDown() {
    }

    // members
    // initialization and clean-up for each test

    @Before
    public void setUp() {
    }

    @After
    public void tearDown() {
    }

    // tests
    // assertEquals(expected, actual);

    /**
     * In this test the server is mocked to
     * simulate a communication exception.
     */
    @Test(expected = WebServiceException.class)
    public void testMockServerException(@Mocked final SDStore_Service service, @Mocked final SDStore port) throws Exception {

        // an "expectation block"
        // One or more invocations to mocked types, causing expectations to be recorded.
        new NonStrictExpectations() {
            {
                //server creates the document with with success
                new SDStore_Service();
                service.getSDStoreImplPort();
                result = port;
                port.createDoc(new DocUserPair());
                result = new WebServiceException("fabricated");
            }
        };

        // Unit under test is exercised.
        StoreClient client = new StoreClient("http://localhost:8081", "sd-store");
        client.createDoc(new DocUserPair());
        //FIXME

    }

    /**
     * In this test the server is mocked to
     * simulate a communication exception on a second call.
     */
    @Test
    public void testMockServerExceptionOnSecondCall() throws Exception {

        // an "expectation block"
        // One or more invocations to mocked types, causing expectations to be recorded.
        new MockUp<SDStore>() {
            @Mock
            public void createDoc(DocUserPair docUserPair) throws DocAlreadyExists_Exception {
                if (x == 2) { throw new WebServiceException("fabricated");}
                x++;
            }

        };

        // Unit under test is exercised.
        StoreClient client = new StoreClient("http://localhost:8081", "sd-store");

        // first call to mocked server
        try {
            client.createDoc(new DocUserPair()); //FIXME
        } catch (WebServiceException e) {
            // exception is not expected
            fail();
        }

        // second call to mocked server
        try {
            client.createDoc(new DocUserPair()); //FIXME
            fail();
        } catch (WebServiceException e) {
            // exception is expected
            assertEquals("fabricated", e.getMessage());
        }
    }

    /**
     * In this test the server is mocked to
     * simulate a Unavailable server
     */
    @Test
    public void testMockServerExceptionServerUnavailable(@Mocked final SDStore_Service service, @Mocked final SDStore port)
            throws Exception {

        // an "expectation block"
        // One or more invocations to mocked types, causing expectations to be recorded.
        new Expectations() {
            {
                new SDStore_Service();
                service.getSDStoreImplPort();
                result = new ConnectException("fabricated");
            }
        };

        // Unit under test is exercised.
        new StoreClient("http://localhost:8081", "sd-store");

    }

    /**
     * In this test the server is mocked to
     * simulate a invalid Invocation Registry
     */
    @Test
    public void testMockServerExceptionRegistryInvocation(@Mocked final UDDINaming uddiNaming) throws Exception {

        // an "expectation block"
        // One or more invocations to mocked types, causing expectations to be recorded.
        new Expectations() {
            {
                new UDDINaming(anyString);
                uddiNaming.lookup(anyString);
                result = new JAXRException("fabricated");
            }
        };

        // Unit under test is exercised.
        new StoreClient("http://localhost:8081", "sd-store");

    }
}
