package sdstorecli;

import java.util.*;

import org.junit.*;

import pt.ulisboa.tecnico.sdis.store.ws.*; // classes generated by wsimport from WSDL
import static org.junit.Assert.*;
import mockit.*;

/**
 *  Test suite
 */
public class StoreClientTest {

    // static members
	
    // one-time initialization and clean-up

    @BeforeClass
    public static void oneTimeSetUp() {
    }

    @AfterClass
    public static void oneTimeTearDown() {
    }


    // members

    // initialization and clean-up for each test

    @Before
    public void setUp() {
    }

    @After
    public void tearDown() {
    }

    // tests
    
}
